services:
  - type: web
    name: env-var-source
    env: ruby
    startCommand: rails s
    envVars: 
      - key: SOME_KEY
        value: SOME_VALUE

  - type: web
    name: env-var-test
    env: ruby
    startCommand: rails s
    envVars:
      - key: SOME_KEY_FROM_OTHER_SOURCE
        fromService:
          type: web
          envVarKey: SOME_KEY
          name: env-var-source
