services:
  - type: web
    name: env-var-test
    env: ruby
    startCommand: rails s
    envVars:
      - fromGroup: envvars
      - key: PROMPT_FOR_THIS_IN_ENVVAR
        sync: false
      - key: ANOTHER_PROMPT_FOR_THIS_IN_ENVVAR
        sync: false

envVarGroups:
  - name: envvars
    envVars:
      - key: PROMPT_FOR_THIS_IN_ENVVAR_GROUP
        sync: false
